# Generated by Django 4.1 on 2022-08-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_slip',
            new_name='votes_to_skip',
        ),
    ]
